### ISSUE TITLE
[exercises lesson06] after switch to user_process , it cannot response svc call

### ISSUE THREAD

**Issue by cuijier** [s-matyukevich/raspberry-pi-os#254]
@xdfm1 Hi xdfm1, i haved seed your exercises  about lesson06, it's work , you are so clever. but according to your code, i have modified little , after run user_process , it can't response svc ，
```
(gdb) 
#0  0x0000000000085200 in ?? ()
#1  0x000000000000003c in user_process () at src/user.c:17
#2  0xffff0000000865f8 in ?? ()
```
can you help me to look it ?
the code link is [here](https://github.com/cuijier/learn_kernel/tree/v1)

**Comment by YBHQ** [comment]
~~~~

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by YBHQ** [comment]
#~~~~

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akshataj96** [comment]
If this is still open, can i start looking into it ? @cuijier
